### ISSUE TITLE
web3.eth.Contract API forces using 32-byte length return value even for `bytes` type

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [substrate-developer-hub/substrate-node-template#86] opened 2020-09-21 13:47 UTC
**Description**

I've been experimenting with precompiles, and I wrote a precompile that just returns "0xdeadbeef" for testing. Nothing special. I was looking for a way to call it in the tests, and I used the web3.eth.Contract API. Even though the return value in the ABI doesn't (seem to) require 32 bytes, the tests would crash if that size isn't in the returned.

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. See the test: https://github.com/PureStake/moonbeam/blob/41b4461aa7e4fc2af9d7e26a9565915985cbd7c8/tests/tests/test-contract-precompiled.ts#L42
2. See the precompiled implementation: https://github.com/PureStake/moonbeam/blob/41b4461aa7e4fc2af9d7e26a9565915985cbd7c8/runtime/src/lib.rs#L319
3. Clone and checkout that commit 41b4461aa7e4fc2af9d7e26a9565915985cbd7c8
4. Build
5. Navigate to the `tests` directory
6. Run the command `npm install` then: `RUST_LOG=runtime=debug MOONBEAM_LOG='info,rpc=trace,evm=trace,ethereum=trace' npm test -- -g precompiled`
7. The test will work fine now.
8. Remove the padding loop shown here then build again: https://github.com/PureStake/moonbeam/blob/41b4461aa7e4fc2af9d7e26a9565915985cbd7c8/runtime/src/lib.rs#L330
9. Run the test again, and you'll get an out-of-bound error

Conclusion: The test will fail if the return value length is < 32 bytes

**Expected vs. Actual Behavior**

It should work without padding, especially that the return value isn't byte32. 

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system: Ubuntu 18.04
- Template version/tag: Commit: 41b4461aa7e4fc2af9d7e26a9565915985cbd7c8 in moonbeam repo
- Rust version (run `rustup show`): 1.47.0-nightly

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._

**Additional Information**

Now I understand this is not the right way to call a precompile (I changed it to eth_call in later commits), but still, this is a bug (apparently) in the contract API of RPC.

**Comment by danforbes** [comment] 2020-09-21 20:37
@TheQuantumPhysicist - thank you for the well-written Issue :pray: Given the fact that the steps to reproduce all relate to code in the Moonbeam repo, I think it may make sense to move this Issue there.

cc: @albertov19 @JoshOrndorff

**Comment by danforbes** [comment] 2020-09-21 20:39
Also cc @sorpaas is this an issue with the EVM pallet?

**Comment by jimmychu0807** [comment] 2021-04-15 11:05
@TheQuantumPhysicist 
This seems to be more about running solidity contract & relating to Purestake/moonbeam project than node-template itself. I am closing this for now. Let me know if you do not think so.

**Closed by jimmychu0807** 2021-04-15 11:05 UTC
Labels: bug
