### ISSUE TITLE
Equivocation

### ISSUE THREAD

**Issue by akaryaginUSETECH** [substrate-developer-hub/substrate-node-template#113] opened 2020-12-02 23:57 UTC
**Description**

Equivocation will not occur unless node has been restarted 

**Steps to Reproduce**

start first validator with config 

./node-template \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9944 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator

start second validator with config 

./node-template \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9946 \
  --rpc-port 9934 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
  --bootnodes /ip4/10.211.55.11/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

**Expected vs. Actual Behavior**

Expected: to get warning about equivocation

Actual: No warning no matter how long nodes are running 

**Environment**

- Operating system:
        Parallels VM
        Host - MacOS
        Guest - Ubuntu
- Template version/tag: v2.0.0
- Rust version (run `rustup show`): 

Default host: x86_64-unknown-linux-gnu rustup home:  /home/alexei/.rustup

installed targets for active toolchain

wasm32-unknown-unknown
x86_64-unknown-linux-gnu
active toolchain

nightly-2020-10-01-x86_64-unknown-linux-gnu (default)
rustc 1.48.0-nightly (ef663a8a4 2020-09-30)

**Logs, Errors or Screenshots**

Unless node is restarted there's no warning 

![Screenshot 2020-12-03 at 01 06 38](https://user-images.githubusercontent.com/74534681/100946918-76e16380-3515-11eb-8c52-992a2e2173bb.png)

**Comment by danforbes** [comment] 2020-12-03 13:27
I was not able to reproduce this issue. In fact, I was not even able to start the second node using the commands you provided. This is the command I had to use to start the second node (I changed the `--base-path` and `--port` parameters):

```
./node-template --base-path /tmp/bob --chain local --alice --port 30334 --ws-port 9946 --rpc-port 9934 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
```

I did not see any warnings about equivocation the first, second, or third time I started the node. In addition to the incorrect commands you provided, it's also odd to me that your node shows 3 blocks finalized. You may have gotten yourself into a weird state and should probably use the `purge-command` subcommand and start over.

```
./node-template purge-chain --chain local --base-path /tmp/alice -y && ./node-template purge-chain --chain local --base-path /tmp/bob -y
```

If you feel this has resolved your problem, can you please close this Issue?

**Comment by akaryaginUSETECH** [comment] 2020-12-03 16:17
have you run it in a separate VMs?

**Comment by danforbes** [comment] 2020-12-03 17:22
No I was running on the same machine I don't typically use VMs for local development. Can you provide steps to reproduce the problem?

**Comment by akaryaginUSETECH** [comment] 2020-12-07 21:29
Bug persists only on local setup(one physical machine, two VMs). On separate physical machines its not present

Steps:

1) Make two VMs with ubuntu 18.04 in parallels (MacOSX)
2) Setup nodes in each VM
3) Run nodes with the config above
4) You won't see equivocation warning unless you restate one of these nodes

**Comment by NukeManDan** [comment] 2021-03-11 19:51
@akaryaginUSETECH checking in here, is this still an issue? If it was resolved, can you share the fix? Happy to reoprn this if you need further support as well.

**Closed by NukeManDan** 2021-03-11 19:51 UTC
Labels: bug

**Comment by akaryaginUSETECH** [comment] 2021-03-12 17:22
@NukeManDan that's fine. It can be only be repeated in local testing environments. It never repeats with --mdns flag and distributed environment(IP4)
